### PR TITLE
Aarch64 coretexa53 linux gnu

### PR DESCRIPTION
**Pull request by necrose99**
CHOST="aarch64-unknown-linux-gnu"
cortex chroot .. sbc's

hoping i can get the python in question to run.

### CODE REVIEW

**Comment by spreequalle** [comment]
Hello Necro, thanks for contributing, 

In the meantime i created an cortex-a53 branch:
https://github.com/spreequalle/gentoo-binhost/tree/aarch64-cortex_a53-linux-gnu
I already had this stuff laying around but never found the time to set it up.

Although i think these packages are not really usable for anyone without any stages,
something that i would like to build in the future using github actions. If you are eager to test stuff i can provide you with a stage.

For your Rock64Pro i suggest creating a branch in your forked repository maybe make it more specific like aarch64-rk3399-liinux-gnu since these big.little configuration are quite special.

**Comment by necrose99** [comment]
still pushing bins manually as rock64 overloaded. 
Rock64Pro & RPI4 can use same bins.  ie 
mcpu=cortex-a72.cortex-a53" **GLIBC** for the most part a few bins like RPi3/4 firmware not so much...  gentoo kernel with panfrost/mali patching errr etc should be fine. 

**https://isshoni.org/pi64pie
https://github.com/sakaki-/gentoo-on-rpi-64bit**
sakaki has profiles , ie pointer to real system profiles sym plus deps. 
@sakaki- i have added/invited  to fork , as She can get a few old bins. 
a few like kde need to be brought more up to date. 

I aim to copy **profile/s** and just hard kill PACKAGES by mask. 
if SBC= **ALLOW/DENY** 
or least have a few mask profiles in repo. branch.. to add to /etc/portage/ 

@pentoo related unmask / temp mask pkgs that fail miserably 
but yeah @metasploit built it.. 
https://www.dropbox.com/sh/gfsfqv3p4lvnzi6/AAAE-Mb_8ko1oX3xSROVkP8ia?dl=0 
respin packages on archive and clean/cleave.  emerge pkg /emerge -U  keep flags etc. 

**_rpi VIDEO_CARDS="fbdev vc4"_** **_rockpro  VIDEO_CARDS="mali panfrost"_** 
same xserver runs  , rock64 pro uses a53 cores x 4 and 2 a72's  sames rpi4 
_if x-sever rebuild for fbdev vc4 mali panfrost_ 
**GLES2** on **pinebook pro** works wayland is a tad iffy..  however i assume the wayland bug will get fixed soonish/hopefully as kde plasma.... 
per @Jannik2099 handy chroot preper for emmc/sd card. 

so little edian and stock stage3  with systemd.  my prefred use. 



one can emerge pkg --nodeps revdep-rebuild wala now systemd .... 
or just rebuild , often easier to rebuild onces emerged. however let me aling my branch as such.
often i've had packages die on sbc... if using scaleway Cavium , and generied chroot with coretex based makefile not much crashes.   only 30 ish E's or 32 ish USD per mo..  8 virt cores and 16 gigs of ram , and docker for emerges nice to have also.. 

my hope is you have an a53 **aarch64 compatible** system or minor variant little edin... 
then a pool of **Generalized packages abound.**  bootstraping KDE xfce lxde etc should be as painless as posible.. and or pool bins .. 

only trivial rebuilds or masks of pkgs. not to your board need be done.

**Comment by necrose99** [comment]
still pushing bins manually as rock64 overloaded. 
Rock64Pro & RPI4 can use same bins.  ie 
https://isshoni.org/pi64pie

**Comment by spreequalle** [comment]
@necrose99 for now next steps regarding this repository is to find a automated solution to generate some clean stages out of the already released binaries.

I have a this workflow mind:
1. use gentoo docker image to create a clean system: ROOT=/NEWSYS emerge -evK system
2. generate new docker image FROM /NEWSYS
3. export stage tarball from new image
4. push image & release stage tarball

This should all be doable using github actions and their free runner, as for qemu emulation, i already tested https://hub.docker.com/r/multiarch/qemu-user-static works like a charm since we have full root privileged runenrs available.

**Comment by necrose99** [comment]
i've had nothing but hell on dockerhub with aaarch64 qemu.. 
FAIL...

**Pull request closed without merging**
